/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author leduy
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    NaiveBayesGenderClassifier model = new NaiveBayesGenderClassifier();

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPredict = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbLongHair = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbLipsThin = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbNoseWide = new javax.swing.JComboBox<>();
        cbNoseLong = new javax.swing.JComboBox<>();
        cbDistanceNoseToLipLong = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtForeheadWidth = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtForeheadHeight = new javax.swing.JTextField();
        btnPredict1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dự đoán giới tính");
        setLocation(new java.awt.Point(480, 150));

        btnPredict.setText("Dự đoán");
        btnPredict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPredictActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setLabelFor(txtResult);
        jLabel6.setText("Result");

        txtResult.setBackground(new java.awt.Color(242, 242, 242));
        txtResult.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtResult.setForeground(new java.awt.Color(255, 0, 51));
        txtResult.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        txtResult.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Long Hair");

        cbLongHair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbLongHair.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "0", "1" }));
        cbLongHair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLongHairActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Lips Thin");

        cbLipsThin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbLipsThin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "0", "1" }));
        cbLipsThin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLipsThinActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Distance Nose to Lip long");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nose Wide");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nose Long");

        cbNoseWide.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbNoseWide.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "0", "1" }));
        cbNoseWide.setName(""); // NOI18N
        cbNoseWide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNoseWideActionPerformed(evt);
            }
        });

        cbNoseLong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbNoseLong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "0", "1" }));
        cbNoseLong.setName(""); // NOI18N
        cbNoseLong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNoseLongActionPerformed(evt);
            }
        });

        cbDistanceNoseToLipLong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbDistanceNoseToLipLong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "0", "1" }));
        cbDistanceNoseToLipLong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDistanceNoseToLipLongActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setLabelFor(txtForeheadWidth);
        jLabel8.setText("Forehead Width");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setLabelFor(txtForeheadHeight);
        jLabel9.setText("Forehead Height");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbLipsThin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbNoseLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbLongHair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(cbNoseWide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtForeheadHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtForeheadWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDistanceNoseToLipLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbLongHair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbNoseWide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNoseLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbLipsThin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDistanceNoseToLipLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtForeheadWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtForeheadHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnPredict1.setLabel("Xóa");
        btnPredict1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPredict1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPredict1)
                .addGap(18, 18, 18)
                .addComponent(btnPredict)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPredict)
                    .addComponent(btnPredict1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPredictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPredictActionPerformed
        try {
            boolean check=true;
            String long_hair = cbLongHair.getItemAt(cbLongHair.getSelectedIndex());
            double forehead_width_cm =Double.parseDouble(txtForeheadWidth.getText()) ;
            String forehead_width_cm_range="";
            if (forehead_width_cm > 11.4 && forehead_width_cm <= 12.425) {
                forehead_width_cm_range = "11.4_12.425";
            } else if (forehead_width_cm > 12.425 && forehead_width_cm <= 13.45) {
                forehead_width_cm_range = "12.425_13.45";
            } else if (forehead_width_cm > 13.45 && forehead_width_cm <= 14.475) {
                forehead_width_cm_range = "13.45_14.475";
            } else if (forehead_width_cm > 14.475 && forehead_width_cm <= 15.5) {
                forehead_width_cm_range = "14.475_15.5";
            }
            else{
                JOptionPane.showMessageDialog(null, "Dữ liệu Forehead width không phù hợp. Xin hãy nhập lại trong khoảng tử 11.4 đến 15.5", "Lỗi", JOptionPane.WARNING_MESSAGE);
                check=false;            
            }
            double forehead_height_cm =Double.parseDouble(txtForeheadHeight.getText()) ;
            String forehead_height_cm_range="";
            if (forehead_height_cm > 5.1 && forehead_height_cm <= 6.1) {
                forehead_height_cm_range = "5.1_6.1";
            } 
            else if (forehead_height_cm > 6.1 && forehead_height_cm <= 7.1) {
                forehead_height_cm_range = "6.1_7.1";
            }
            else{
                JOptionPane.showMessageDialog(null, "Dữ liệu Forehead width không phù hợp. Xin hãy nhập lại trong khoảng tử 5.1 đến 7.1", "Lỗi", JOptionPane.WARNING_MESSAGE);
                check=false;
            }
            String nose_wide = cbNoseWide.getItemAt(cbNoseWide.getSelectedIndex());
            String nose_long = cbNoseLong.getItemAt(cbNoseLong.getSelectedIndex());
            String lips_thin = cbLipsThin.getItemAt(cbLipsThin.getSelectedIndex());
            String distance_nose_to_lip_long = cbDistanceNoseToLipLong.getItemAt(cbDistanceNoseToLipLong.getSelectedIndex());
            
            if(long_hair.equals("None") || nose_wide.equals("None") || nose_long.equals("None") || lips_thin.equals("None") || distance_nose_to_lip_long.equals("None")){
                JOptionPane.showMessageDialog(null, "Xin hãy điền đầy đủ thông tin", "Lỗi", JOptionPane.ERROR_MESSAGE);
                check=false;
            }
            
            if(check){
                String predict = model.predict(long_hair, forehead_width_cm_range, forehead_height_cm_range, nose_wide, nose_long, lips_thin, distance_nose_to_lip_long);
                txtResult.setText(predict);
            }
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
                  
    }//GEN-LAST:event_btnPredictActionPerformed

    private void cbLongHairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLongHairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLongHairActionPerformed

    private void cbNoseWideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNoseWideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNoseWideActionPerformed

    private void cbNoseLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNoseLongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNoseLongActionPerformed

    private void cbLipsThinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLipsThinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLipsThinActionPerformed

    private void cbDistanceNoseToLipLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDistanceNoseToLipLongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDistanceNoseToLipLongActionPerformed

    private void btnPredict1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPredict1ActionPerformed
        cbLongHair.setSelectedIndex(0);
        cbNoseWide.setSelectedIndex(0);
        cbNoseLong.setSelectedIndex(0);
        cbLipsThin.setSelectedIndex(0);
        cbDistanceNoseToLipLong.setSelectedIndex(0);
        txtForeheadWidth.setText("");
        txtForeheadHeight.setText("");
        txtResult.setText("");
    }//GEN-LAST:event_btnPredict1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPredict;
    private javax.swing.JButton btnPredict1;
    private javax.swing.JComboBox<String> cbDistanceNoseToLipLong;
    private javax.swing.JComboBox<String> cbLipsThin;
    private javax.swing.JComboBox<String> cbLongHair;
    private javax.swing.JComboBox<String> cbNoseLong;
    private javax.swing.JComboBox<String> cbNoseWide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtForeheadHeight;
    private javax.swing.JTextField txtForeheadWidth;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
